### PR TITLE
Update metadata for better charmhub output

### PR DESCRIPTION
**Pull request by mthaddon**
Ensure `metadata.yaml` meets new documentation requirements

### CODE REVIEW

**Review by amandahla — DISMISSED** [review]
LGTM

**Review by arturo-seijas — COMMENTED** [review]
Can you please add the `source`too?

**Review by arturo-seijas — COMMENTED** [review]
Can you please add the `source`too?

**Comment by mthaddon** [comment]
> Can you please add the `source`too?

Have added that now, can you take another look pls?

**Review by arturo-seijas — DISMISSED** [review]

**Review by amandahla — APPROVED** [review]
LGTM

**Review by arturo-seijas — APPROVED** [review]

**Pull request merged**
